---
title: "Independent Impact"
author: "Christiaan Pauw & Alex Howard"
format:
  revealjs:
    theme: sky # Options include: beige, blood, dark, default, dracula, league, moon, night, serif, simple, sky, solarized
    css: custom.scss
---

## Problem / Opportunity

::: {.smaller-list}

* Africa has a rapidly growing population with a significant portion of young people. 

* Africa has many economic, social and ecological challenges.

*  **The people are not the problem, they are the solution!**

* Emerging technology like the Hedera network provides opportunity to empower and mobilise this massive human capital for beneficial action on a large scale. 

:::

## Independent Impact  {style="text-align: center;"}

:::{style="display: flex; justify-content: center; align-items: center; text-align: center; height: 100%; padding: 0 15%;  font-size: 1.2em;  max-width: 100%;  margin: auto;"}


Independent Impact is developing an open platform for reporting, quantifying, verifying and tokenising human impact in a trustworthy way.
:::

___ 

### Built for the long term {style="text-align: center;"}


The platform is designed with solid philosophical, conceptual and technical foundations to evolve and sustain in the long term

* A new paradigm for Impact Accounting suited to Africa's needs 
* Elegant conceptual framework 
* Right technology for the job

___

### A new Impact Accounting paradigm {style="text-align: center;"}

Independent Impact represents a new way of looking at Impact Accounting that is:

* Open but meritocratic 
* Transparent, not prescriptive 
* Immutable yet accessible

___

### A new Impact Accounting paradigm {style="text-align: center;"}

#### Open but meritocratic

:::{style="display:  font-size: 0.65em;  max-width: 100%;  margin: auto;"}

**Participation is open** to individual and legal entities as implementers, validators, verifiers, and methodology developers

**Reputation is earned** through quality contributions and peer evaluation

**Reputation governs** the impact of a participant's actions 
:::

___

Independent Impact is:

* Geared to a bottom-up approach 
* No limits to starting participation 
* Impact and permissions graded by reputation 
* Reputation for all agents and controls (e.g. methods) 
* Peer evaluation at every stage 
* Incentives for continual quality improvements 

___

### A new Impact Accounting paradigm {style="text-align: center;"}

#### Transparent, not prescriptive

Independent Impact is designed so users can clearly interpret every quantified outcome while choosing the metrics, assurance levels, and estimation approaches that meet their needs.

* Composable impact metrics 
* Clear disclosure of methodologies 
* Semantic representation of all artefacts makes comparison easy

___

### A new Impact Accounting paradigm {style="text-align: center;"}

#### Immutable yet accessible

Proven distributed technologies protect artefacts and transactions while making every action auditable. Users can interrogate projects, credentials, and impact claims in depth.

* Immutable artefact storage 
* Fast, fair and immutable event ordering
* Queryable history of actions, controls and artefacts

## Conceptual Framework 

Long-term sustainability flows from an elegant but comprehensive conceptual framework

* Based on a core ontology
* Everything is semantic 
* Everything is reviewable
* Everything has reputation
* A methodology is a function


<!--
3. Impact and reward on any scale (individual to national)
4. Ground truthing and verification at any level (like citizen science) -->

___ 

## Conceptual Framework

### Core ontology

Independent Impact is built on a fundamental ontology: **Anthropogenic Impact Accounting Ontology (AIAO)**.

[AIAO](https://w3id.org/aiao)  and its related ontologies provide a comprehensive framework for defining and quantifying human impact on the environment and society. 

___ 

The core Independent Impact team was instrumental in developing AIAO and its three related ontologies:

[Impact Ontology](https://w3id.org/impactont) 

[Claim Ontology](https://w3id.org/claimont) 

[Information Communication Ontology](https://w3id.org/infocomm)


## Conceptual Framework

### Everything is semantic

Discoverablity and interoperability are built in from the start by adhering to W3C Semantic Web Standards. 

### Everything has reputation

People, organisations and methodologies have reputation that is earned through quality contributions and peer evaluation.

### A methodology is a function

A methodology is a function that takes inputs and produces a quantum on the metric being measured.

## Technology {style="text-align: center;"}

::: {.smaller-list}
Long-term sustainability flows from an elegant and efficient technology stack and architecture

* **Hedera Consensus Service** for event journaling 
* **W3C Decentralised Identifiers** (DID) for identification 
* **W3C Verifiable Credentials** for credential issuance and verification 
* **IPFS** for immutable distributed document storage 
* **Jellyfish** for verifiable compute 
* **Fluree** as a cryptographically secured, immutable, time-travelable semantic database 
* **Hedera Token Service** for tokenisation of verified impacts 

:::

## What we offer

Trust and transparency for different user:

::: {.smaller-list}

* **Individuals and communities**: Everyone can act as sponsor, implementer or fact checker / validator / verifier
* **Implementers**: tools to quantify impacts and obtain verification of their impacts
* **Validators /Verifiers**: tools to validate and verify reported impacts
* **Sponsors**: tools to set standards and targets and reward verified impacts
* **Buyers**: tools to discover, evaluate and purchase verified impacts

:::

##  Market Size

#### Traditional tokenised impacts

:::{.smallest-list}
* Carbon credits
* Water benefit certificates, etc.

:::

#### Traditional development aid / relief

:::{.smallest-list}
* Achieve aims through a *Pay-for-Success* model

:::

#### Education 

:::{.smallest-list}
* Learning tokens

:::
#### Community initiatives

:::{.smallest-list}
* Set local goals
* Mobilise local action

:::

## Status and Roadmap

::: columns

::: {.column width="50%"}

#### Done ✅ 

:::{.smallest-list}
* Developer portal launched 
* User registration: Project implementer, validator, verifier
* Project registration and PDD development
* PDD validation 
* Monitoring report submission
* Monitoring report verification
* Certificate issuance 
* Migration to Fluree back-end

:::

:::

::: {.column width="50%"}

#### In Process 🚧

:::{.smallest-list}
* Reputation system
* Methodology registry
* First mile survey sollution

:::

:::

:::

___

#### Planned 🔭

* Wallet integration
* UI migration to Golang back-end
* Learning tokens integration and pilot project
* Indicator portal
* Methodology portal



## Why we believe in Independent Impact

:::{.smaller-list}

* It's inspiring vision gives rise to a new paradigm in impact accounting with is suited to Africa's potential 

* It is built on an elegant and fruitful conceptual framework that will enable the development of a rich ecosystem 

* It uses the best technology for the job (HCS, IPFS, Fluree and W3C standards) 

* Nova Institute is driving the development and implementation for our own projects 

* Collaborators who have proven long-term commitment (LFDT Learning Tokens)

:::
<!--
**Radically open** means that anyone can join and participate and that participation can take place at many levels. This must include:

 - unemployed youth in a village 
 - entrepreneurs 
 - small and large NGOs 
 - governments 
 - corporations 
 
**Radically open** means there are no mediators for participation, but that *what* can be done depends on the reputation gained through quality participation  

### Transparency and Reputation

**Transparency** builds trust when all events are fairly ordered, visible and discoverable

Everything has **reputation** and every action has consequences. This mean the system evolves towards better quality.  -->
