---
title: "Hackathon notes"
format: html
---

## Project 

The Project must be capable of being successfully installed and running consistently on the platform for which it is intended and must function as depicted in the video and/or expressed in the text description. Platforms: A submitted Project must run on the platform for which it is intended and which is specified in the Submission Requirements. 

## Pitch Deck
Participants must submit a Pitch Deck that clearly outlines the Problem, Solution, Product, Market Size, Target Customer as well as the Value Proposition and Ask. 

## New & Existing
Projects must be either newly created by the Entrant or, if the Entrant’s Project existed prior to the Hackathon Submission Period, must have been significantly updated after the start of the Hackathon Submission Period. Entrants should explain how their Project was significantly updated during the Submission Period. 

## Submission Requirements 
Submissions to the Hackathon must meet the following requirements:

 - Include a Project built with the required developer tools and meets the above Project Requirements. 
 - Include a text description that should explain the features and functionality of your Project. The text description should include: 
  * Policy description Workflow description [Optional, but encouraged] 
  * Comparative analysis to similar methodologies 
  * Include a demonstration video of your Project. The video portion of the Submission: 
      + should be less than three (3) minutes should include footage that shows the Project functioning on the device for which it was built should describe the solution relevance of the project. 
      + must be uploaded to and made publicly visible on YouTube, Vimeo, Facebook Video, or Youku, and 
      + a link to the video must be provided on the submission form on the Hackathon Website; and must not include third party trademarks, or copyrighted music or other material unless the Entrant has permission to use such material. 
      
## Testing Access  
Testing Access must be provided to an Entrant’s working Project for judging and testing by providing a link to a website, functioning demo, or a test build. If Entrant’s website is private, Entrant must include login credentials in its testing instructions. The Entrant must make the Project available free of charge and without any restriction, for testing, evaluation and use by the Organising Teams, Sponsors, Administrators and Judges until the Judging Period ends.  

## Team Representation 
If a team or organization is entering the Hackathon, they must appoint and authorize one individual (the “Representative”) to represent, act, and enter a Submission, on their behalf. The Representative must meet the eligibility requirements above. By entering a Submission on the Hackathon Website on behalf of a team or organization you represent and warrant that you are the Representative authorized to act on behalf of your team or organization. 

## Intellectual Property 
Your Submission must: 

 - (a) be your (or your Team, or Organization’s) original work product;
 - (b) be solely owned by you, your Team, your Organization with no other person or entity having any right or interest in it; and 
 - (c) not violate the intellectual property rights or other rights including but not limited to copyright, trademark, patent, contract, and/or privacy rights, of any other person or entity. 

An Entrant may contract with a third party for technical assistance to create the Submission provided the Submission components are solely the Entrant’s work product and the result of the Entrant’s ideas and creativity, and the Entrant owns all rights to them. An Entrant may submit a Submission that includes the use of open source software or hardware, provided the Entrant complies with applicable open source licenses and, as part of the Submission, creates software that enhances and builds upon the features and functionality included in the underlying open source product

## Judging Criteria ]
Entries will be judged on the following equally weighted criteria, and according to the sole and absolute discretion of the judges: 

 - **Originality** Is the methodology unique? Note that this doesn't preclude improving a methodology for implementation and completeness. 
 - **Functionality** Does the methodology work as designed? Is it applicable and easy to use? 
 - **Completeness** Does the submission include all of the required elements, including complete documentation, 
  * a video explainer, 
  * functional helpers, 
  * relevant tools, 
  * methodology variations, 
  * example data,
  * social media post, etc.? 
- **Problem/Solution Significance**. 
- **Team-Product Fit **
- **Market Opportunity**. 
- **Pitch Deck**

## Detailed Process Flow: 
### Stage Description 
#### Payment/Action Roadmap 

Submission Teams submit a clear roadmap with two major milestones, outlining the project goals and progress. The road map is reviewed and approved before further action. 

**KYC/KYB completion** required for Prize disbursement. 50% Prize Money Payment First Prize payment upon initial approval and meeting of all minimum requirements. 50% of the total Prize paid. 

**Milestone 1 Payment** Payment based on progress report and achievement of Milestone 1 objectives. 25% of the total Prize paid. 

**Milestone 2 Payment** Final payment upon completion of the project and achievement of the final milestone goals. 25% of the total Prize paid.

